///*
// * This source file was generated by the Gradle 'init' task
// */
//package org.example;
//import org.example.entities.Ticket;
//import org.example.entities.User;
//import org.example.services.UserBookingService;
//import org.example.util.UserServiceUtil;
//
//import java.io.IOException;
//import java.util.*;
//import java.util.stream.Collectors;
//import java.util.function.Predicate;
//public class App {
//
//
//    public static void main(String[] args){
//        System.out.println("Running train booking system.");
//        Scanner sc = new Scanner(System.in);
//        int option = 0;
//        UserBookingService userBookingService ;
//        try{
//            userBookingService = new UserBookingService();
//        }
//        catch(IOException ex){
//            System.out.println("There is something wrong");
//            return;
//        }
//        while(option!=7){
//            System.out.println("Fetch Bookings");
//            System.out.println("1. Sign Up");
//            System.out.println("2. LogIn");
//            System.out.println("3. Fetch Bookings");
//            System.out.println("4. Search Trains");
//            System.out.println("5. Book a Seat");
//            System.out.println("6. Cancel my Bookings");
//            System.out.println("7. Exit the App");
//
//            option = sc.nextInt();
//
//            switch(option){
//                case 1:
//                    System.out.print("Enter the username to signup : ");
//                    String nameToSignup = sc.next();
//                    System.out.print("Enter the password to signup : ");
//                    String passwordToSignup = sc.next();
//                    User userToSignup = new User(nameToSignup, passwordToSignup,
//                            UserServiceUtil.hashPassword(passwordToSignup),
//                            new ArrayList<>(), UUID.randomUUID().toString()));
//                    userBookingService.signUp(userToSignup);
//                    break;
//                case 2:
//                    System.out.print("Enter the username to Login : ");
//                    String nameToLogin = sc.next();
//                    System.out.println("Enter the password to signup");
//                    String passwordToLogin = sc.next();
//                    User userLogin =
//            }
//        }
//    }
//}






//package org.example;
//
//import ticket.booking.entities.Train;
//import ticket.booking.entities.User;
//import ticket.booking.service.UserBookingService;
//import ticket.booking.util.UserServiceUtil;


package org.example;
import org.example.entities.Ticket;
import org.example.entities.Train;
import org.example.entities.User;
//import org.example.services.UserBookingService;
import org.example.services.TrainService;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;


import java.io.IOException;
//import java.util.*;
//import java.util.stream.Collectors;
//import java.util.function.Predicate;
//
//import java.io.IOException;
//import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.UUID;
//import org.postgresql.Driver;

public class App {

    public static void main(String[] args) {

        System.out.println("Running Train Booking System");
        TrainService trainService = new TrainService();
        Scanner scanner = new Scanner(System.in);
        int option = 0;

        Train trainSelectedForBooking = null;
        // ✅ REMOVED: User currentUser = null;  // This was unused and causing confusion

        while(option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            System.out.print("Enter your choice: ");

            try {
                option = scanner.nextInt();
                scanner.nextLine();
            } catch (Exception e) {
                System.out.println("Invalid input. Please enter a number.");
                scanner.nextLine();
                continue;
            }

            switch (option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();
                    UserBookingService.signup(nameToSignUp, passwordToSignUp);
                    break;

                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter the password to login");
                    String passwordToLogin = scanner.next();
                    UserBookingService.login(nameToLogin, passwordToLogin);
                    break;

                case 3:
                    User currUser = UserServiceUtil.getCurrentUser();
                    if (currUser == null) {
                        System.out.println("Please login first.");
                    } else {
                        UserBookingService.fetchBookings(currUser);
                    }
                    break;

                case 4:
                    System.out.println("Type your source station");
                    String source = scanner.next();
                    System.out.println("Type your destination station");
                    String dest = scanner.next();
                    trainService.searchTrains(source, dest).forEach(t ->
                            System.out.println("Train ID: " + t.getTrainId()
                                    + ", Train No: " + t.getTrainNo()));
                    break;

                case 5: {
                    User currUser1 = UserServiceUtil.getCurrentUser();
                    if (currUser1 == null) {
                        System.out.println("Please login first.");
                        break;
                    }

                    System.out.print("Enter Train ID: ");
                    String trainId = scanner.nextLine();

                    System.out.print("Enter source station: ");
                    String source1 = scanner.nextLine();

                    System.out.print("Enter destination station: ");
                    String destination = scanner.nextLine();

                    System.out.print("Enter seat row number: ");
                    int row = scanner.nextInt();

                    System.out.print("Enter seat number: ");
                    int seat = scanner.nextInt();
                    scanner.nextLine();

                    UserBookingService.bookSeat(
                            currUser1,
                            trainId,
                            row,
                            seat,
                            source1,
                            destination
                    );
                }
                break;

                case 6: {
                    User currUser3 = UserServiceUtil.getCurrentUser();
                    if (currUser3 == null) {
                        System.out.println("Please login first.");
                        break;
                    }

                    System.out.print("Enter Ticket ID to cancel: ");
                    String ticketIdStr = scanner.nextLine();

                    UserBookingService.cancelBooking(
                            currUser3,
                            UUID.fromString(ticketIdStr)
                    );
                }
                break;

                case 7:
                    System.out.println("Exiting...");
                    System.exit(0);

                default:
                    System.out.println("Invalid option. Please try again.");
                    break;
            }
        }
        scanner.close();



        //        System.out.println("Running Train Booking System");
//        TrainService trainService = new TrainService();
//        Scanner scanner = new Scanner(System.in);
//        int option = 0;
////        UserBookingService userBookingService;
////        try{
////            userBookingService = new UserBookingService();
////            System.out.println("UserBookingService initialized successfully!");
////        }catch(IOException ex){
////            System.err.println("Error initializing UserBookingService: " + ex.getMessage());
////            ex.printStackTrace();
////            return;
////        }
//
//        Train trainSelectedForBooking = null;
//        User currentUser = null;
//        while(option!=7){
//            System.out.println("Choose option");
//            System.out.println("1. Sign up");
//            System.out.println("2. Login");
//            System.out.println("3. Fetch Bookings");
//            System.out.println("4. Search Trains");
//            System.out.println("5. Book a Seat");
//            System.out.println("6. Cancel my Booking");
//            System.out.println("7. Exit the App");
//            System.out.print("Enter your choice: ");
//
//            try {
//                option = scanner.nextInt();
//                scanner.nextLine(); // consume newline
//            } catch (Exception e) {
//                System.out.println("Invalid input. Please enter a number.");
//                scanner.nextLine(); // clear invalid input
//                continue;
//            }
////            option = scanner.nextInt();
////            Train trainSelectedForBooking = new Train();
//            switch (option){
//                case 1:
//                    System.out.println("Enter the username to signup");
//                    String nameToSignUp = scanner.next();
//                    System.out.println("Enter the password to signup");
//                    String passwordToSignUp = scanner.next();
//
//                    UserBookingService.signup(nameToSignUp, passwordToSignUp);
////                    User userToSignup = new User(nameToSignUp, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
////                    userBookingService.signUp(userToSignup);
//                    break;
//                case 2:
//                    System.out.println("Enter the username to Login");
//                    String nameToLogin = scanner.next();
//                    System.out.println("Enter the password to signup");
//                    String passwordToLogin = scanner.next();
//
//                    UserBookingService.login(nameToLogin, passwordToLogin);
//
////                    User userToLogin = new User(nameToLogin, passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
////                    try{
////                        userBookingService = new UserBookingService(userToLogin);
////                    }catch (IOException ex){
////                        return;
////                    }
//                    break;
//                case 3:
//
//                    User currUser = UserServiceUtil.getCurrentUser();
//
//                    if (currUser == null) {
//                        System.out.println("Please login first.");
//                    } else {
//                        UserBookingService.fetchBookings(currUser);
//                    }
//
////                    UserBookingService.fetchBookings(UserServiceUtil.getCurrentUser());
////                    System.out.println("Fetching your bookings");
////                    userBookingService.fetchBookings();
//                    break;
//                case 4:
//                    System.out.println("Type your source station");
//                    String source = scanner.next();
//                    System.out.println("Type your destination station");
//                    String dest = scanner.next();
//
//                    trainService.searchTrains(source, dest).forEach(t ->System.out.println("Train ID: " + t.getTrainId()
//                                                    + ", Train No: " + t.getTrainNo()));
//
////                    List<Train> trains = userBookingService.getTrains(source, dest);
////                    int index = 1;
////                    for (Train t: trains){
////                        System.out.println(index+" Train id : "+t.getTrainId());
////                        for (Map.Entry<String, String> entry: t.getStationTimes().entrySet()){
////                            System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
////                        }
////                    }
////                    System.out.println("Select a train by typing 1,2,3...");
////                    trainSelectedForBooking = trains.get(scanner.nextInt());
//                    break;
//                case 5:
//                    User currUser1 = UserServiceUtil.getCurrentUser();
//
//                    if (currUser1 == null) {
//                        System.out.println("Please login first.");
//                        break;
//                    }
//
//                    System.out.print("Enter Train ID: ");
//                    String trainId = scanner.nextLine();
//
//                    System.out.print("Enter source station: ");
//                    String source1 = scanner.nextLine();
//
//                    System.out.print("Enter destination station: ");
//                    String destination = scanner.nextLine();
//
//                    System.out.print("Enter seat row number: ");
//                    int row = scanner.nextInt();
//
//                    System.out.print("Enter seat number: ");
//                    int seat = scanner.nextInt();
//                    scanner.nextLine(); // consume newline
//
//                    UserBookingService.bookSeat(
//                            currUser1,  // ✅ Changed from currentUser to currUser1
//                            trainId,
//                            row,
//                            seat,
//                            source1,
//                            destination
//                    );
//                    break;
//                case 6 : {
//                    User currUser3 = UserServiceUtil.getCurrentUser();
//
//                    if (currUser3 == null) {
//                        System.out.println("Please login first.");
//                        break;
//                    }
//
//                    System.out.print("Enter Ticket ID to cancel: ");
//                    String ticketIdStr = scanner.nextLine();
//
//                    UserBookingService.cancelBooking(
//                            currUser3,
//                            UUID.fromString(ticketIdStr)
//                    );
//                }
//                break;
//
//                case 7 : System.exit(0);
//                default:
//                    break;
//            }
//        }
    }
}
